<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wUpw4Ks' shared service.

return $this->privates['.service_locator.wUpw4Ks'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagnerepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'cateRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true],
    'categorie' => ['privates', '.errored..service_locator.wUpw4Ks.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.wUpw4Ks": it references class "App\\Entity\\Categorie" but no such service exists.'],
    'comrepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService.php', true],
    'cr' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
    'scr' => ['privates', 'App\\Repository\\SousCategorieRepository', 'getSousCategorieRepositoryService.php', true],
]);
