<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vp1Cw8G' shared service.

return $this->privates['.service_locator.vp1Cw8G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'coursOnerepo' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
]);
