<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::deleteFormateur' => ['privates', '.service_locator.VNvP_gf', 'get_ServiceLocator_VNvPGfService.php', true],
    'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController::tableUsersCommande' => ['privates', '.service_locator.FRxrk_E', 'get_ServiceLocator_FRxrkEService.php', true],
    'App\\Controller\\CampagneController::allCampagnes' => ['privates', '.service_locator.colFYAN', 'get_ServiceLocator_ColFYANService.php', true],
    'App\\Controller\\CampagneController::campagneUser' => ['privates', '.service_locator.96C9_sl', 'get_ServiceLocator_96C9SlService.php', true],
    'App\\Controller\\CampagneController::index' => ['privates', '.service_locator.3oMVbOD', 'get_ServiceLocator_3oMVbODService.php', true],
    'App\\Controller\\ContactController::index' => ['privates', '.service_locator.OtLCyeI', 'get_ServiceLocator_OtLCyeIService.php', true],
    'App\\Controller\\CoursController::allCours' => ['privates', '.service_locator.AwfL7HQ', 'get_ServiceLocator_AwfL7HQService.php', true],
    'App\\Controller\\CoursController::finaliserCommande' => ['privates', '.service_locator.qYp9khN', 'get_ServiceLocator_QYp9khNService.php', true],
    'App\\Controller\\CoursController::findCoursOneSousCategorie' => ['privates', '.service_locator.BjEics2', 'get_ServiceLocator_BjEics2Service.php', true],
    'App\\Controller\\CoursController::findOneCour' => ['privates', '.service_locator.vp1Cw8G', 'get_ServiceLocator_Vp1Cw8GService.php', true],
    'App\\Controller\\CoursController::findOneCourCommande' => ['privates', '.service_locator.i9JTcQQ', 'get_ServiceLocator_I9JTcQQService.php', true],
    'App\\Controller\\CoursController::findOneCoursCategorie' => ['privates', '.service_locator.wUpw4Ks', 'get_ServiceLocator_WUpw4KsService.php', true],
    'App\\Controller\\CoursController::mesCours' => ['privates', '.service_locator.AuwXEVK', 'get_ServiceLocator_AuwXEVKService.php', true],
    'App\\Controller\\CoursController::searchAction' => ['privates', '.service_locator.GdxNST2', 'get_ServiceLocator_GdxNST2Service.php', true],
    'App\\Controller\\PanierController::panier' => ['privates', '.service_locator.r_.7K2_', 'get_ServiceLocator_R_7K2Service.php', true],
    'App\\Controller\\PanierController::validerCommande' => ['privates', '.service_locator.r_.7K2_', 'get_ServiceLocator_R_7K2Service.php', true],
    'App\\Controller\\PosteController::RegisterFormateur' => ['privates', '.service_locator.C4XeI2o', 'get_ServiceLocator_C4XeI2oService.php', true],
    'App\\Controller\\PosteController::addCours' => ['privates', '.service_locator.J8ZkkQY', 'get_ServiceLocator_J8ZkkQYService.php', true],
    'App\\Controller\\PosteController::addCours1' => ['privates', '.service_locator.J8ZkkQY', 'get_ServiceLocator_J8ZkkQYService.php', true],
    'App\\Controller\\PosteController::findOnePoste' => ['privates', '.service_locator.tCcyqiW', 'get_ServiceLocator_TCcyqiWService.php', true],
    'App\\Controller\\PosteController::poste' => ['privates', '.service_locator.A1vG5oe', 'get_ServiceLocator_A1vG5oeService.php', true],
    'App\\Controller\\RegistrationController::editAction' => ['privates', '.service_locator.DEVOM3r', 'get_ServiceLocator_DEVOM3rService.php', true],
    'App\\Controller\\RegistrationController::editPhoto' => ['privates', '.service_locator.nyWh7Wz', 'get_ServiceLocator_NyWh7WzService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.Z9dMtpR', 'get_ServiceLocator_Z9dMtpRService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.eM2YqBr', 'get_ServiceLocator_EM2YqBrService.php', true],
    'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\AdminController:deleteFormateur' => ['privates', '.service_locator.VNvP_gf', 'get_ServiceLocator_VNvPGfService.php', true],
    'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController:tableUsersCommande' => ['privates', '.service_locator.FRxrk_E', 'get_ServiceLocator_FRxrkEService.php', true],
    'App\\Controller\\CampagneController:allCampagnes' => ['privates', '.service_locator.colFYAN', 'get_ServiceLocator_ColFYANService.php', true],
    'App\\Controller\\CampagneController:campagneUser' => ['privates', '.service_locator.96C9_sl', 'get_ServiceLocator_96C9SlService.php', true],
    'App\\Controller\\CampagneController:index' => ['privates', '.service_locator.3oMVbOD', 'get_ServiceLocator_3oMVbODService.php', true],
    'App\\Controller\\ContactController:index' => ['privates', '.service_locator.OtLCyeI', 'get_ServiceLocator_OtLCyeIService.php', true],
    'App\\Controller\\CoursController:allCours' => ['privates', '.service_locator.AwfL7HQ', 'get_ServiceLocator_AwfL7HQService.php', true],
    'App\\Controller\\CoursController:finaliserCommande' => ['privates', '.service_locator.qYp9khN', 'get_ServiceLocator_QYp9khNService.php', true],
    'App\\Controller\\CoursController:findCoursOneSousCategorie' => ['privates', '.service_locator.BjEics2', 'get_ServiceLocator_BjEics2Service.php', true],
    'App\\Controller\\CoursController:findOneCour' => ['privates', '.service_locator.vp1Cw8G', 'get_ServiceLocator_Vp1Cw8GService.php', true],
    'App\\Controller\\CoursController:findOneCourCommande' => ['privates', '.service_locator.i9JTcQQ', 'get_ServiceLocator_I9JTcQQService.php', true],
    'App\\Controller\\CoursController:findOneCoursCategorie' => ['privates', '.service_locator.wUpw4Ks', 'get_ServiceLocator_WUpw4KsService.php', true],
    'App\\Controller\\CoursController:mesCours' => ['privates', '.service_locator.AuwXEVK', 'get_ServiceLocator_AuwXEVKService.php', true],
    'App\\Controller\\CoursController:searchAction' => ['privates', '.service_locator.GdxNST2', 'get_ServiceLocator_GdxNST2Service.php', true],
    'App\\Controller\\PanierController:panier' => ['privates', '.service_locator.r_.7K2_', 'get_ServiceLocator_R_7K2Service.php', true],
    'App\\Controller\\PanierController:validerCommande' => ['privates', '.service_locator.r_.7K2_', 'get_ServiceLocator_R_7K2Service.php', true],
    'App\\Controller\\PosteController:RegisterFormateur' => ['privates', '.service_locator.C4XeI2o', 'get_ServiceLocator_C4XeI2oService.php', true],
    'App\\Controller\\PosteController:addCours' => ['privates', '.service_locator.J8ZkkQY', 'get_ServiceLocator_J8ZkkQYService.php', true],
    'App\\Controller\\PosteController:addCours1' => ['privates', '.service_locator.J8ZkkQY', 'get_ServiceLocator_J8ZkkQYService.php', true],
    'App\\Controller\\PosteController:findOnePoste' => ['privates', '.service_locator.tCcyqiW', 'get_ServiceLocator_TCcyqiWService.php', true],
    'App\\Controller\\PosteController:poste' => ['privates', '.service_locator.A1vG5oe', 'get_ServiceLocator_A1vG5oeService.php', true],
    'App\\Controller\\RegistrationController:editAction' => ['privates', '.service_locator.DEVOM3r', 'get_ServiceLocator_DEVOM3rService.php', true],
    'App\\Controller\\RegistrationController:editPhoto' => ['privates', '.service_locator.nyWh7Wz', 'get_ServiceLocator_NyWh7WzService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.Z9dMtpR', 'get_ServiceLocator_Z9dMtpRService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.eM2YqBr', 'get_ServiceLocator_EM2YqBrService.php', true],
    'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
]));
