<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FRxrk_E' shared service.

return $this->privates['.service_locator.FRxrk_E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commanderepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
    'formateurRepository' => ['privates', 'App\\Repository\\FormateurRepository', 'getFormateurRepositoryService.php', true],
    'ur' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
