<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerByUVeAP\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerByUVeAP/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerByUVeAP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerByUVeAP\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerByUVeAP\srcApp_KernelProdContainer([
    'container.build_hash' => 'ByUVeAP',
    'container.build_id' => 'd5ad77be',
    'container.build_time' => 1586887389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerByUVeAP');
