<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3mclTtL\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3mclTtL/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container3mclTtL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container3mclTtL\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container3mclTtL\srcApp_KernelProdContainer([
    'container.build_hash' => '3mclTtL',
    'container.build_id' => '311d48ab',
    'container.build_time' => 1571068774,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3mclTtL');
