<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'titreCours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'petitDescription', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'exigence', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'etiquette', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'visibilite', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'souscategorie', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'chapitres', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'commandes', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'universite'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'titreCours', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'petitDescription', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'exigence', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'etiquette', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'visibilite', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'souscategorie', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'chapitres', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'commandes', '' . "\0" . 'App\\Entity\\Cours' . "\0" . 'universite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreCours(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreCours', []);

        return parent::getTitreCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreCours(string $titreCours): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreCours', [$titreCours]);

        return parent::setTitreCours($titreCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetitDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetitDescription', []);

        return parent::getPetitDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetitDescription(string $petitDescription): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetitDescription', [$petitDescription]);

        return parent::setPetitDescription($petitDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getExigence(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExigence', []);

        return parent::getExigence();
    }

    /**
     * {@inheritDoc}
     */
    public function setExigence(string $exigence): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExigence', [$exigence]);

        return parent::setExigence($exigence);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(int $prix): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtiquette(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtiquette', []);

        return parent::getEtiquette();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtiquette(string $etiquette): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtiquette', [$etiquette]);

        return parent::setEtiquette($etiquette);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibilite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibilite', []);

        return parent::getVisibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibilite(bool $visibilite): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibilite', [$visibilite]);

        return parent::setVisibilite($visibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree(string $duree): \App\Entity\Cours
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getChapitres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChapitres', []);

        return parent::getChapitres();
    }

    /**
     * {@inheritDoc}
     */
    public function setChapitres($chapitres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChapitres', [$chapitres]);

        return parent::setChapitres($chapitres);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommandes($commandes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommandes', [$commandes]);

        return parent::setCommandes($commandes);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getSouscategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSouscategorie', []);

        return parent::getSouscategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSouscategorie($souscategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSouscategorie', [$souscategorie]);

        return parent::setSouscategorie($souscategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversite', []);

        return parent::getUniversite();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversite($universite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversite', [$universite]);

        return parent::setUniversite($universite);
    }

}
