<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aSIovln' shared service.

return $this->privates['.service_locator.aSIovln'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagnerepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'cateRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true],
    'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService.php', true],
    'commentrepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService.php', true],
    'coursrepo' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
    'cr' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
    'fr' => ['privates', 'App\\Repository\\FormateurRepository', 'getFormateurRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'souscatrepo' => ['privates', 'App\\Repository\\SousCategorieRepository', 'getSousCategorieRepositoryService.php', true],
]);
