<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eM2YqBr' shared service.

return $this->privates['.service_locator.eM2YqBr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authenticationUtils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
    'cr' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
]);
