<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VNvP_gf' shared service.

return $this->privates['.service_locator.VNvP_gf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'formateur' => ['privates', '.errored..service_locator.VNvP_gf.App\\Entity\\Formateur', NULL, 'Cannot autowire service ".service_locator.VNvP_gf": it references class "App\\Entity\\Formateur" but no such service exists.'],
]);
