#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /security_logout
    # app/config/routing_dev.yml

allCours:
     path: /{_locale}
     controller: App\Controller\CoursController::allCours

