<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.tCcyqiW.App\Entity\Poste' shared service.

include_once $this->targetDirs[3].'/src/Entity/Poste.php';

return $this->privates['.errored..service_locator.tCcyqiW.App\\Entity\\Poste'] = new \App\Entity\Poste();
