<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8cTsi7l' shared service.

return $this->privates['.service_locator.8cTsi7l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'chapitre' => ['privates', '.errored..service_locator.8cTsi7l.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.8cTsi7l": it references class "App\\Entity\\Chapitre" but no such service exists.'],
    'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
]);
