<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yMEQeCZ' shared service.

return $this->privates['.service_locator.yMEQeCZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'universite' => ['privates', '.errored..service_locator.yMEQeCZ.App\\Entity\\Universite', NULL, 'Cannot autowire service ".service_locator.yMEQeCZ": it references class "App\\Entity\\Universite" but no such service exists.'],
]);
