<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BjEics2' shared service.

return $this->privates['.service_locator.BjEics2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagnerepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'catrepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true],
    'comrepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService.php', true],
    'cr' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
    'souscat' => ['privates', '.errored..service_locator.BjEics2.App\\Entity\\SousCategorie', NULL, 'Cannot autowire service ".service_locator.BjEics2": it references class "App\\Entity\\SousCategorie" but no such service exists.'],
    'souscatrepo' => ['privates', 'App\\Repository\\SousCategorieRepository', 'getSousCategorieRepositoryService.php', true],
]);
