<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.W4Ih6zC' shared service.

return $this->privates['.service_locator.W4Ih6zC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService.php', true],
]);
