<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SChEJbl' shared service.

return $this->privates['.service_locator.SChEJbl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'universityRepository' => ['privates', 'App\\Repository\\UniversiteRepository', 'getUniversiteRepositoryService.php', true],
]);
