<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QO69bMs' shared service.

return $this->privates['.service_locator.QO69bMs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'chapitre' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService.php', true],
    'parcour' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
]);
