<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ULMBmjr' shared service.

return $this->privates['.service_locator.ULMBmjr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.ULMBmjr.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.ULMBmjr": it references class "App\\Entity\\User" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'users' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
]);
