<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._tbTmkU' shared service.

return $this->privates['.service_locator._tbTmkU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService.php', true],
]);
