<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Hq6ECO6' shared service.

return $this->privates['.service_locator.Hq6ECO6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagnes' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'commandes' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
    'cour' => ['privates', '.errored..service_locator.Hq6ECO6.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.Hq6ECO6": it references class "App\\Entity\\Cours" but no such service exists.'],
]);
