<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UJhfId9' shared service.

return $this->privates['.service_locator.UJhfId9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cour' => ['privates', '.errored..service_locator.UJhfId9.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.UJhfId9": it references class "App\\Entity\\Cours" but no such service exists.'],
    'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
]);
