<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.96C9_sl' shared service.

return $this->privates['.service_locator.96C9_sl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagne' => ['privates', '.errored..service_locator.96C9_sl.App\\Entity\\Campagne', NULL, 'Cannot autowire service ".service_locator.96C9_sl": it references class "App\\Entity\\Campagne" but no such service exists.'],
    'campagneRepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'cr' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true],
    'scr' => ['privates', 'App\\Repository\\SousCategorieRepository', 'getSousCategorieRepositoryService.php', true],
]);
