<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vLgvRBQ' shared service.

return $this->privates['.service_locator.vLgvRBQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commande' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
    'cr' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
]);
