<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTcNjIcM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTcNjIcM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTcNjIcM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTcNjIcM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTcNjIcM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TcNjIcM',
    'container.build_id' => '578dc866',
    'container.build_time' => 1586887394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTcNjIcM');
