<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHikLW5C\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHikLW5C/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHikLW5C.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHikLW5C\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHikLW5C\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HikLW5C',
    'container.build_id' => 'e8b18d25',
    'container.build_time' => 1591350475,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHikLW5C');
