<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v7bI6lj' shared service.

return $this->privates['.service_locator.v7bI6lj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagneRepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
    'coursrepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
]);
