<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.C7tnfb8' shared service.

return $this->privates['.service_locator.C7tnfb8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campagneId' => ['privates', '.errored..service_locator.C7tnfb8.App\\Entity\\Campagne', NULL, 'Cannot autowire service ".service_locator.C7tnfb8": it references class "App\\Entity\\Campagne" but no such service exists.'],
    'campagnerepository' => ['privates', 'App\\Repository\\CampagneRepository', 'getCampagneRepositoryService.php', true],
]);
