<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \App\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'parcoursEdu', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'opportinute', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'attentes', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'motivation', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'perspective', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'commande'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'parcoursEdu', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'opportinute', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'attentes', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'motivation', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'perspective', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'commentaire', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Projet' . "\0" . 'commande'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcoursEdu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcoursEdu', []);

        return parent::getParcoursEdu();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcoursEdu(string $parcoursEdu): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcoursEdu', [$parcoursEdu]);

        return parent::setParcoursEdu($parcoursEdu);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportinute(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportinute', []);

        return parent::getOpportinute();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportinute(string $opportinute): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportinute', [$opportinute]);

        return parent::setOpportinute($opportinute);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttentes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttentes', []);

        return parent::getAttentes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttentes(string $attentes): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttentes', [$attentes]);

        return parent::setAttentes($attentes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivation', []);

        return parent::getMotivation();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivation(string $motivation): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivation', [$motivation]);

        return parent::setMotivation($motivation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerspective(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerspective', []);

        return parent::getPerspective();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerspective(string $perspective): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerspective', [$perspective]);

        return parent::setPerspective($perspective);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(?string $telephone): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire(?string $commentaire): \App\Entity\Projet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommande', []);

        return parent::getCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommande($commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommande', [$commande]);

        return parent::setCommande($commande);
    }

}
